name: eeg_env
channels:
    - defaults
dependencies:
    - python=3.8.5
    - pip=20.2.3
    - cudatoolkit=10.2.89
    - gurobi=9.1.1
    - notebook=6.1.4
    - numpy=1.19.1
    - scikit-image=0.17.2
    - scipy=1.5.2
    - six=1.15.0
    - pip:
        - ipdb~=0.13.7
        - plotly~=4.14.3
        - pillow~=7.2.0
        - fire~=0.4.0
        - visdom~=0.1.8.9
        - opencv-python~=4.4.0.46
        - torchnet~=0.0.4
